.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH MUMUDVB 1 "21 June 2009" "MuMuDVB v1.5.5"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
MuMuDVB \- Multicast a DVB transponder over multiples ip addresses

.SH SYNOPSIS
.B mumudvb
.RI [ options ]
.B -c
conf_file
.br
.B mumudvb
.RI [ options ]
\-\-config
conf_file

.SH DESCRIPTION
\fBMuMuDVB\fP is a program who can redistribute stream from DVB on a network, in multicast or in HTTP unicast. It's main feature is to take a whole transponder and put each channel on a different multicast IP. 

Website : http://mumudvb.braice.net/

.SH OPTIONS
The following options are provided by MuMuDVB : 
.TP
.B \-c, \-\-config conf_file
Path to the config file
.TP
.B \-s, \-\-signal
Display signal power
.TP
.B \-t, \-\-traffic
Display channels traffic
.TP
.B \-d, \-\-debug
Don't deamonize
.TP
.B \-h, \-\-help
Display Help
.TP
.B \-v
More Verbose
.TP
.B \-q
More quiet

.SH SEE ALSO
The program is documented in README and for french speaking people in README-fr.

.SH AUTHOR
Upstream author:
.br
Brice DUBOST <mumudvb@braice.net>
.br
Contributors:
.br
Stéphane Glondu <glondu@crans.ens-cachan.fr> (makefile cleaning, man page, debian package)
.br
Manuel SABBAN <manu@crans.ens-cachan.fr> (use of getopt)
.br
Acknowledgements:
.br
Dave CHAPMAN (for writing dvbstream)
.PP
This manual page was written by Stephane Glondu <stephane.glondu@crans.org> and Brice DUBOST <mumudvb@braice.net>.
